# Copyright (c) 2025 uDocket. All Rights Reserved.
#
# PROPRIETARY AND CONFIDENTIAL
#
# This software is the confidential and proprietary information of uDocket.
# You shall not disclose such confidential information and shall use it only
# in accordance with the terms of the license agreement you entered into with uDocket.
"""uDocket shared utility helpers."""

from . import json_utils
from .json_utils import (
    JSONArray,
    JSONObject,
    JSONPrimitive,
    JSONValue,
    coerce_bool,
    coerce_float,
    coerce_int,
    coerce_json_array,
    coerce_json_object,
    coerce_json_value,
    coerce_object_dict,
    coerce_object_list,
    coerce_str,
    coerce_str_dict,
    coerce_str_list,
    ensure_json_object,
    is_json_scalar,
    json_object_to_dict,
    json_payload,
    load_json_object,
    load_json_value,
    merge_json_objects,
    normalize_json_object,
    normalize_mapping,
    normalize_mapping_optional,
    parse_json_object,
    parse_json_value,
    parse_json_value_strict,
    read_json_object,
    read_json_value,
    stringify_json,
    stringify_pretty,
    write_json_object,
    write_json_value,
)

__all__ = [
    "JSONArray",
    "JSONObject",
    "JSONPrimitive",
    "JSONValue",
    "coerce_bool",
    "coerce_float",
    "coerce_int",
    "coerce_json_array",
    "coerce_json_object",
    "coerce_json_value",
    "coerce_object_dict",
    "coerce_object_list",
    "coerce_str",
    "coerce_str_dict",
    "coerce_str_list",
    "ensure_json_object",
    "is_json_scalar",
    "json_object_to_dict",
    "json_payload",
    "json_utils",
    "load_json_object",
    "load_json_value",
    "merge_json_objects",
    "normalize_json_object",
    "normalize_mapping",
    "normalize_mapping_optional",
    "parse_json_object",
    "parse_json_value",
    "parse_json_value_strict",
    "read_json_object",
    "read_json_value",
    "stringify_json",
    "stringify_pretty",
    "write_json_object",
    "write_json_value",
]
